name: Run node files

on:
  issues:
    types: [opened, edited]

jobs:
  run-main:
    name: Run main.js
    runs-on: ubuntu-latest
    steps:
      - id: node-setup
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: dependency-install
        name: Install npm dependencies
        run: npm ci
      - id: run-main
        name: Run main.js
        # env:
        #   GITHUB_EVENT: ${{ github.event }}
        run: node ./main.js
